compile:
	g++ server.cpp -o server -std=c++11
	g++ client.cpp -o client -std=c++11

server:
	g++ server.cpp -o server -std=c++11 

client:
	g++ client.cpp -o client -std=c++11

clean:
	rm server client